---
repos:
  # YAML auto-formatters
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 0.9.0
    hooks:
      - id: yamlfix
  # GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
      - id: check-ast
      - id: check-docstring-first
      - id: check-yaml
        exclude: .*ci.yml
      - id: check-toml
      - id: check-added-large-files
  # Python auto-formatters
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries=120
          - --wrap-descriptions=120
  - repo: https://github.com/ikamensh/flynt
    rev: '0.76'
    hooks:
      - id: flynt
  # BASH auto-formatters
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        args: [-i=4]
