---
exclude: build-support/alpha-build/core|build-support/git-bash-integration
repos:
  # YAML auto-formatters
  - repo: https://github.com/lyz-code/yamlfix/
    rev: ""
    hooks:
      # On Windows, this writes \r\n newlines that need to be fixed by the next hook
      - id: yamlfix
  # Prettier auto-formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ""
    hooks:
      # On Windows, this writes \r\n newlines that need to be fixed by the next hook
      - id: prettier
  # GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
      - id: check-ast
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  # Python auto-formatters
  - repo: https://github.com/PyCQA/autoflake
    rev: ""
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
  - repo: https://github.com/PyCQA/docformatter
    rev: ""
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries={{cookiecutter.line_length}}
          - --wrap-descriptions={{cookiecutter.line_length}}
  - repo: https://github.com/ikamensh/flynt
    rev: ""
    hooks:
      - id: flynt
  - repo: https://github.com/pycqa/isort
    rev: ""
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-path=pyproject.toml]
  # Black also applies to notebooks
  - repo: https://github.com/psf/black
    rev: ""
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: ""
    hooks:
      - id: ruff-format
        name: ruff format
      - id: ruff
        name: ruff lint
  # Python linters
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: ""
    hooks:
      - id: flakeheaven
        additional_dependencies: [wemake-python-styleguide, flake8-annotations]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: ""
    hooks:
      - id: python-bandit-vulnerability-check
        name: bandit
        args: [--configfile pyproject.toml]
  - repo: https://github.com/pycqa/pylint
    rev: ""
    hooks:
      - id: pylint
        args: [--rcfile=pyproject.toml]
  # JUPYTER auto-formatters
  - repo: https://github.com/kynan/nbstripout
    rev: ""
    hooks:
      - id: nbstripout
  # BASH auto-formatters
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: ""
    hooks:
      - id: shfmt
        args: [-i=4]
  # BASH linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: ""
    hooks:
      - id: shellcheck
        args: [-x]
  # YAML linters
  - repo: https://github.com/adrienverge/yamllint.git
    rev: ""
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: ""
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.yml]
  # NOTE! Direct usage of flake8 is disabled (uncomment to use flake8 specifically)
  #       flake8 is used via flakeheaven which is preferred because it allows running flake8 with plugins on legacy code
  #  - repo: https://github.com/pycqa/flake8
  #    rev: ''
  #    hooks:
  #      - id: flake8
  # NOTE! Usafe of mypy from the mirror is disabled, prefer the local installation of mypy such that one could have
  #       access to all the type annotations exported by third party libraries.
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: ''
  #    hooks:
  #      - id: mypy
  #        additional_dependencies:
  #          - sqlalchemy[mypy]
  #          - pydantic
