[tool.pytest.ini_options]
addopts = "--cov={{cookiecutter.project_name}} --cov-fail-under=75 -vv --durations=10"

[tool.isort]
profile = 'black'
line_length = 120

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.bandit]
skips = ["B101"]

[tool.flakeheaven]
format = "colored"
# baseline = ".baseline.txt"  # Uncomment this and run `flakeheaven baseline > .baseline.txt` to ignore legacy errors

[tool.flakeheaven.plugins]
wemake-python-styleguide = ["+*"]
flake8-annotations = ["+*"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-debugger = ["+*"]
flake8-eradicate = ["+*"]
flake8-quotes = ["+*"]
flake8-rst-docstrings = ["+*"]
flake8-string-format = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
flake8-spellcheck = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]
#pylint = ["+*"]  # Uncomment if you want to enable pylint and use it on top of the baseline
#flake8-bandit = ["+*"]
#flake8-docstrings = ["+*"]
#flake8-isort = ["+*"]

[tool.pylint.MASTER]
extension-pkg-whitelist = "pydantic"

[tool.pylint.FORMAT]
max-line-length = 120
disable = [
    "import-error",  # pre-commit does not give access to full env
    "fixme",
    "logging-format-interpolation",
    "logging-fstring-interpolation",
    "logging-not-lazy",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
]
